### ISSUE TITLE
ERROR TypeError: Cannot call method 'http' of undefined

### ISSUE THREAD

**Issue by beauraF** [ryandao/hubot-timezone#3]
Hi,

I have this issue when I use your script :

> May 25 23:45:41 sd-91132 hubot[29175]: [Wed May 25 2016 23:45:41 GMT+0200 (CEST)] ERROR TypeError: Cannot call method 'http' of undefined
> May 25 23:45:41 sd-91132 hubot[29175]: at Response.http (/home/hubot/myhubot/node_modules/hubot/src/response.coffee:109:12)
> May 25 23:45:41 sd-91132 hubot[29175]: at getTimezoneInfo (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:38:3)
> May 25 23:45:41 sd-91132 hubot[29175]: at sendLocalTime (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:78:5)
> May 25 23:45:41 sd-91132 hubot[29175]: at convertTime (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:93:5)
> May 25 23:45:41 sd-91132 hubot[29175]: at TextListener.callback (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:117:5)
> May 25 23:45:41 sd-91132 hubot[29175]: at /home/hubot/myhubot/node_modules/hubot/src/listener.coffee:65:12
> May 25 23:45:41 sd-91132 hubot[29175]: at allDone (/home/hubot/myhubot/node_modules/hubot/src/middleware.coffee:44:37)
> May 25 23:45:41 sd-91132 hubot[29175]: at /home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
> May 25 23:45:41 sd-91132 hubot[29175]: at Object.async.eachSeries (/home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
> May 25 23:45:41 sd-91132 hubot[29175]: at Object.async.reduce (/home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
> May 25 23:45:41 sd-91132 hubot[29175]: at /home/hubot/myhubot/node_modules/hubot/src/middleware.coffee:49:13
> May 25 23:45:41 sd-91132 hubot[29175]: at process._tickCallback (node.js:448:13)

Any idea ?

Thanks you.

**Comment by ryandao** [comment]
Thanks for reporting. I just published an update with the fix. Can you try again?

**Comment by beauraF** [comment]
Hi @ryandao, 

Same issue with the fix. 

> May 30 14:23:13 sd-91132 hubot[9040]: [Mon May 30 2016 14:23:13 GMT+0200 (CEST)] INFO [Incoming] beauraF: Jeeves time in Sidney
May 30 14:23:13 sd-91132 hubot[9040]: [Mon May 30 2016 14:23:13 GMT+0200 (CEST)] INFO Message sent to hubot brain.
May 30 14:23:13 sd-91132 hubot[9040]: [Mon May 30 2016 14:23:13 GMT+0200 (CEST)] ERROR TypeError: Cannot call method 'http' of undefined
May 30 14:23:13 sd-91132 hubot[9040]: at Response.http (/home/hubot/myhubot/node_modules/hubot/src/response.coffee:109:12)
May 30 14:23:13 sd-91132 hubot[9040]: at getTimezoneInfo (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:37:3)
May 30 14:23:13 sd-91132 hubot[9040]: at sendLocalTime (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:77:5)
May 30 14:23:13 sd-91132 hubot[9040]: at convertTime (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:92:5)
May 30 14:23:13 sd-91132 hubot[9040]: at TextListener.callback (/home/hubot/myhubot/node_modules/hubot-timezone/src/timezone.coffee:116:5)
May 30 14:23:13 sd-91132 hubot[9040]: at /home/hubot/myhubot/node_modules/hubot/src/listener.coffee:65:12
May 30 14:23:13 sd-91132 hubot[9040]: at allDone (/home/hubot/myhubot/node_modules/hubot/src/middleware.coffee:44:37)
May 30 14:23:13 sd-91132 hubot[9040]: at /home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
May 30 14:23:13 sd-91132 hubot[9040]: at Object.async.eachSeries (/home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
May 30 14:23:13 sd-91132 hubot[9040]: at Object.async.reduce (/home/hubot/myhubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
May 30 14:23:13 sd-91132 hubot[9040]: at /home/hubot/myhubot/node_modules/hubot/src/middleware.coffee:49:13
May 30 14:23:13 sd-91132 hubot[9040]: at process._tickCallback (node.js:448:13)

**Comment by beauraF** [comment]
Its good. Thank you very much for your speed and for this script !
